services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn backend.main:app --reload"
    runtime: python-3.9.13 